/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RANDOM_H_RPCGEN
#define _RANDOM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct bounds {
	int min;
	int max;
};
typedef struct bounds bounds;


#define RANDOM 0x20000001
#define VERSION_UN 1

#if defined(__STDC__) || defined(__cplusplus)
#define SET_BOUNDS 0
extern  void * set_bounds_1(bounds *, CLIENT *);
extern  void * set_bounds_1_svc(bounds *, struct svc_req *);
#define NEXT_RANDOM 1
extern  int * next_random_1(void *, CLIENT *);
extern  int * next_random_1_svc(void *, struct svc_req *);
extern int random_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SET_BOUNDS 0
extern  void * set_bounds_1();
extern  void * set_bounds_1_svc();
#define NEXT_RANDOM 1
extern  int * next_random_1();
extern  int * next_random_1_svc();
extern int random_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_bounds (XDR *, bounds*);
extern  bool_t xdr_bounds (XDR *, bounds*);

#else /* K&R C */
extern bool_t xdr_bounds ();
extern bool_t xdr_bounds ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RANDOM_H_RPCGEN */
