/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "random.h"
static unsigned int min = 0;
static unsigned int max = 10;

void *
set_bounds_1_svc(bounds *argp, struct svc_req *rqstp)
{
	static char * result;

	min = argp->min;
	max = argp->max;

	return (void *) &result;
}

int *
next_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	result = rand() % (max - min + 1) + min;
	return &result;
}
