/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "random.h"

bool_t
xdr_bounds (XDR *xdrs, bounds *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}
